### ISSUE TITLE
CRASH ON LUNAR CLIENT

### ISSUE THREAD

**Issue by jjkjkjj** [LvStrnggg/argon#10]
20.56.01---- Minecraft Crash Report ----
20.56.01// Uh... Did I do that?
20.56.01Time: 2024-12-09 20:56:01
20.56.01Description: Rendering screen
20.56.01java.lang.NullPointerException: Cannot read field "screen" because "dev.lvstrng.argon.Argon.mc" is null
20.56.01 at Genesis//dev.lvstrng.argon.gui.ClickGui.render(ClickGui.java:52)
20.56.01 at Genesis//net.minecraft.client.gui.screens.Screen.renderWithTooltip(SourceFile:117)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.md1c8f8b$lambda$lunar$drawScreenEvents$7$5(SourceFile:3017)
20.56.01 at Genesis//com.moonsworth.lunar.client.ROHROCIIHOCRHCORHOIROIIRHRROOO.OCROHIOOIOCCRICHHHICIHIOHOHHCI.CIROHCHIOHHIHICHOCIRRCHHCCICCO(Unknown Source)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.lunar$drawScreenEvents(SourceFile:2990)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.redirect_lunar$render$drawScreen$v1_20_0(SourceFile:2983)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$redirect_lunar$render$drawScreen$v1_20_0$297(SourceFile)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.wrapOperation_onRenderScreen(SourceFile:11118)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.render(SourceFile:913)
20.56.01 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1285)
20.56.01 at Genesis//net.minecraft.client.Minecraft.forceSetScreen(SourceFile:2322)
20.56.01 at Genesis//dev.lvstrng.argon.module.modules.client.ClickGUI.onEnable(ClickGUI.java:59)
20.56.01 at Genesis//dev.lvstrng.argon.module.Module.toggle(Module.java:35)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.lambda$onButtonPress$1(ModuleManager.java:114)
20.56.01 at java.base@21.0.1/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.onButtonPress(ModuleManager.java:112)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.lambda$fire$0(ButtonListener.java:23)
20.56.01 at java.base@21.0.1/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.fire(ButtonListener.java:23)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fireImpl(EventManager.java:40)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fire(EventManager.java:22)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.handler_onPress(SourceFile:3619)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.keyPress(SourceFile)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$8(SourceFile:499)
20.56.01 at Genesis//net.minecraft.util.thread.BlockableEventLoop.execute(SourceFile:108)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$9(SourceFile:499)
20.56.01 at Genesis//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
20.56.01 at Genesis//org.lwjgl.system.JNI.invokeV(Native Method)
20.56.01 at Genesis//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.pollEvents(SourceFile:150)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)
20.56.01 at Genesis//com.mojang.blaze3d.platform.Window.updateDisplay(SourceFile:303)
20.56.01 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1307)
20.56.01 at Genesis//net.minecraft.client.Minecraft.run(SourceFile:882)
20.56.01 at Genesis//net.minecraft.client.main.Main.main(SourceFile:256)
20.56.01 at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.01 at java.base@21.0.1/java.lang.reflect.Method.invoke(Unknown Source)
20.56.01 at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
20.56.01 at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.01 at java.base@21.0.1/java.lang.reflect.Method.invoke(Unknown Source)
20.56.01 at app//com.moonsworth.lunar.genesis.CCHOHIOHRHCOOIIHHHRIHIHHCCOOIO.HIIHCRICCORIOOHOIOHHRIHCHHHRCI(Unknown Source)
20.56.01 at app//com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
20.56.01 at app//com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
20.56.01A detailed walkthrough of the error, its code path and all known details is as follows:
20.56.01---------------------------------------------------------------------------------------
20.56.01-- Head --
20.56.01Thread: Render thread
20.56.01Stacktrace:
20.56.01 at Genesis//dev.lvstrng.argon.gui.ClickGui.render(ClickGui.java:52)
20.56.01 at Genesis//net.minecraft.client.gui.screens.Screen.renderWithTooltip(SourceFile:117)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.md1c8f8b$lambda$lunar$drawScreenEvents$7$5(SourceFile:3017)
20.56.01 at Genesis//com.moonsworth.lunar.client.ROHROCIIHOCRHCORHOIROIIRHRROOO.OCROHIOOIOCCRICHHHICIHIOHOHHCI.CIROHCHIOHHIHICHOCIRRCHHCCICCO(Unknown Source)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.lunar$drawScreenEvents(SourceFile:2990)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.redirect$zgj000$lunar$render$drawScreen$v1_20_0(SourceFile:2983)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$redirect$zgj000$lunar$render$drawScreen$v1_20_0$297(SourceFile)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.wrapOperation$bpb000$onRenderScreen(SourceFile:11118)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.render(SourceFile:913)
20.56.01 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1285)
20.56.01 at Genesis//net.minecraft.client.Minecraft.forceSetScreen(SourceFile:2322)
20.56.01 at Genesis//dev.lvstrng.argon.module.modules.client.ClickGUI.onEnable(ClickGUI.java:59)
20.56.01 at Genesis//dev.lvstrng.argon.module.Module.toggle(Module.java:35)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.lambda$onButtonPress$1(ModuleManager.java:114)
20.56.01 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.onButtonPress(ModuleManager.java:112)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.lambda$fire$0(ButtonListener.java:23)
20.56.01 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.fire(ButtonListener.java:23)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fireImpl(EventManager.java:40)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fire(EventManager.java:22)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.handler$cbc000$onPress(SourceFile:3619)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.keyPress(SourceFile)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$8(SourceFile:499)
20.56.01 at Genesis//net.minecraft.util.thread.BlockableEventLoop.execute(SourceFile:108)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$9(SourceFile:499)
20.56.01 at Genesis//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
20.56.01 at Genesis//org.lwjgl.system.JNI.invokeV(Native Method)
20.56.01 at Genesis//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.pollEvents(SourceFile:150)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)
20.56.01-- Screen render details --
20.56.01Details:
20.56.01 Screen name: dev.lvstrng.argon.gui.ClickGui
20.56.01 Mouse location: Scaled: (489, 277). Absolute: (978.000000, 555.000000)
20.56.01 Screen size: Scaled: (720, 424). Absolute: (1440, 847). Scale factor of 2.000000
20.56.01Stacktrace:
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.lunar$drawScreenEvents(SourceFile:2990)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.redirect$zgj000$lunar$render$drawScreen$v1_20_0(SourceFile:2983)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$redirect$zgj000$lunar$render$drawScreen$v1_20_0$297(SourceFile)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.wrapOperation$bpb000$onRenderScreen(SourceFile:11118)
20.56.01 at Genesis//net.minecraft.client.renderer.GameRenderer.render(SourceFile:913)
20.56.01 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1285)
20.56.01 at Genesis//net.minecraft.client.Minecraft.forceSetScreen(SourceFile:2322)
20.56.01 at Genesis//dev.lvstrng.argon.module.modules.client.ClickGUI.onEnable(ClickGUI.java:59)
20.56.01 at Genesis//dev.lvstrng.argon.module.Module.toggle(Module.java:35)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.lambda$onButtonPress$1(ModuleManager.java:114)
20.56.01 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.module.ModuleManager.onButtonPress(ModuleManager.java:112)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.lambda$fire$0(ButtonListener.java:23)
20.56.01 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.01 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.fire(ButtonListener.java:23)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fireImpl(EventManager.java:40)
20.56.01 at Genesis//dev.lvstrng.argon.event.EventManager.fire(EventManager.java:22)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.handler$cbc000$onPress(SourceFile:3619)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.keyPress(SourceFile)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$8(SourceFile:499)
20.56.01 at Genesis//net.minecraft.util.thread.BlockableEventLoop.execute(SourceFile:108)
20.56.01 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$9(SourceFile:499)
20.56.01 at Genesis//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
20.56.01 at Genesis//org.lwjgl.system.JNI.invokeV(Native Method)
20.56.01 at Genesis//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.pollEvents(SourceFile:150)
20.56.01 at Genesis//com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)
20.56.02 at Genesis//com.mojang.blaze3d.platform.Window.updateDisplay(SourceFile:303)
20.56.02 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1307)
20.56.02 at Genesis//net.minecraft.client.Minecraft.run(SourceFile:882)
20.56.02 at Genesis//net.minecraft.client.main.Main.main(SourceFile:256)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.CCHOHIOHRHCOOIIHHHRIHIHHCCOOIO.HIIHCRICCORIOOHOIOHHRIHCHHHRCI(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
20.56.02-- Screen render details --
20.56.02Details:
20.56.02 Screen name: dev.lvstrng.argon.gui.ClickGui
20.56.02 Mouse location: Scaled: (489, 277). Absolute: (978.000000, 555.000000)
20.56.02 Screen size: Scaled: (720, 424). Absolute: (1440, 847). Scale factor of 2.000000
20.56.02Stacktrace:
20.56.02 at Genesis//net.minecraft.client.renderer.GameRenderer.render(SourceFile:913)
20.56.02 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1285)
20.56.02 at Genesis//net.minecraft.client.Minecraft.forceSetScreen(SourceFile:2322)
20.56.02 at Genesis//dev.lvstrng.argon.module.modules.client.ClickGUI.onEnable(ClickGUI.java:59)
20.56.02 at Genesis//dev.lvstrng.argon.module.Module.toggle(Module.java:35)
20.56.02 at Genesis//dev.lvstrng.argon.module.ModuleManager.lambda$onButtonPress$1(ModuleManager.java:114)
20.56.02 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.02 at Genesis//dev.lvstrng.argon.module.ModuleManager.onButtonPress(ModuleManager.java:112)
20.56.02 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.lambda$fire$0(ButtonListener.java:23)
20.56.02 at java.base/java.util.ArrayList.forEach(Unknown Source)
20.56.02 at Genesis//dev.lvstrng.argon.event.events.ButtonListener$ButtonEvent.fire(ButtonListener.java:23)
20.56.02 at Genesis//dev.lvstrng.argon.event.EventManager.fireImpl(EventManager.java:40)
20.56.02 at Genesis//dev.lvstrng.argon.event.EventManager.fire(EventManager.java:22)
20.56.02 at Genesis//net.minecraft.client.KeyboardHandler.handler$cbc000$onPress(SourceFile:3619)
20.56.02 at Genesis//net.minecraft.client.KeyboardHandler.keyPress(SourceFile)
20.56.02 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$8(SourceFile:499)
20.56.02 at Genesis//net.minecraft.util.thread.BlockableEventLoop.execute(SourceFile:108)
20.56.02 at Genesis//net.minecraft.client.KeyboardHandler.lambda$setup$9(SourceFile:499)
20.56.02 at Genesis//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
20.56.02 at Genesis//org.lwjgl.system.JNI.invokeV(Native Method)
20.56.02 at Genesis//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
20.56.02 at Genesis//com.mojang.blaze3d.systems.RenderSystem.pollEvents(SourceFile:150)
20.56.02 at Genesis//com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)
20.56.02 at Genesis//com.mojang.blaze3d.platform.Window.updateDisplay(SourceFile:303)
20.56.02 at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1307)
20.56.02 at Genesis//net.minecraft.client.Minecraft.run(SourceFile:882)
20.56.02 at Genesis//net.minecraft.client.main.Main.main(SourceFile:256)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.CCHOHIOHRHCOOIIHHHRIHIHHCCOOIO.HIIHCRICCORIOOHOIOHHRIHCHHHRCI(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
20.56.02-- Uptime --
20.56.02Details:
20.56.02 JVM uptime: 188.924s
20.56.02 Wall uptime: 105.199s
20.56.02 High-res time: 7550.733s
20.56.02 Client ticks: 1233 ticks / 61.650s
20.56.02Stacktrace:
20.56.02 at Genesis//net.minecraft.client.Minecraft.fillReport(SourceFile:2501)
20.56.02 at Genesis//net.minecraft.client.Minecraft.emergencySaveAndCrash(SourceFile:949)
20.56.02 at Genesis//net.minecraft.client.Minecraft.run(SourceFile:902)
20.56.02 at Genesis//net.minecraft.client.main.Main.main(SourceFile:256)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
20.56.02 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
20.56.02 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.CCHOHIOHRHCOOIIHHHRIHIHHCCOOIO.HIIHCRICCORIOOHOIOHHRIHCHHHRCI(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
20.56.02 at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
20.56.02-- Last reload --
20.56.02Details:
20.56.02 Reload number: 1
20.56.02 Reload reason: initial
20.56.02 Finished: Yes
20.56.02 Packs: lunar, vanilla, fabric, autosprintfix, caffeineconfig, cloth-config, completedshieldfix, enhancedblockentities, entityculling, exordium, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, gpu_tape, ias, immediatelyfast, indium, iris, lithium, microdurability, microdurability-core, modmenu, notenoughanimations, noxesium, reeses-sodium-options, replaymod, sodium, sodium-extra, vmp, replaymod_lang

**Comment by ImLegiitXD** [comment]
it doesn't works on lunar, try Feather instead..
